name: ci
on:
  push:
    branches:
      - dev
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SERVER: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}
      - name: Composer Dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Lint
        run: composer lint
      - name: Unit Tests
        run: composer test
      #- name: Codecov
      #  uses: codecov/codecov-action@v1.0.5
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
